title: gilfoyle_v2
url: https://pro-utkarshM.github.io
author: pro-utkarshM
email: projects.utkarshMaurya@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Utkarsh is a software engineer and hobbyist kernel developer currently based in India.  
  He occasionally blogs about software development, startups, and kernel development.

  Hey, if you'd like to connect, feel free to set up a meeting using the links above!
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: pro-utkarshM-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://utkarshs-terminal.netlify.app/
      icon: linux
      color: yellow
    - url: https://twitter.com/gilfoyle_v2
      icon: twitter-square
      color: cyan
    - url: https://linkedin.com/in/utkarsh-maurya-connect
      icon: linkedin
      color: teal
    - url: https://cal.com/utkarsh-maurya/30min
      icon: calendar-alt
      color: yellow
    - url: https://www.youtube.com/@tss.TheSkillShow
      icon: youtube
      color: red
    - url: https://github.com/pro-utkarshM
      icon: github-square
      color: white
    - url: https://www.instagram.com/utkar_sh_/
      icon: instagram
      color: pink

  avatar_source: local
  avatar_path: /public/avatar.jpg
  # avatar_path: /public/avatar.gif

# Build settings
theme: jekyll-dash

plugins:
  - liquid-md5
  - jekyll/tagging


